In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

In [60]:
PCA_Data = pd.read_csv('PCA_Data_Chms_1_223.csv')
AE_Data = pd.read_csv('AE_Data_Chms_1_223.csv')

In [61]:
Add_Features = pd.read_csv('Urine_Chms_1_223_Dataset.csv')[['Пол', 'Возраст', 'Цвет']]

In [62]:
PCA_Data = pd.concat([Add_Features, PCA_Data], axis=1)

In [63]:
AE_Data = pd.concat([Add_Features, AE_Data], axis=1)

In [64]:
PCA_Data

     Пол  Возраст          Цвет         0         1         2  TOTAL Dataset
0      m     24.0     COLORLESS  0.177378  0.088835 -0.014477    8.0    Chm1
1      m     24.0     COLORLESS  0.222739  0.051637 -0.039282    8.0    Chm1
2      m     24.0     COLORLESS  0.165340  0.069660 -0.021116    8.0    Chm1
3      m     24.0     COLORLESS  0.200208  0.051914 -0.022559    8.0    Chm1
4      m     24.0     COLORLESS  0.154772  0.075796 -0.014855    8.0    Chm1
...   ..      ...           ...       ...       ...       ...    ...     ...
2062   m     75.0  LIGHT YELLOW  0.175095 -0.036475 -0.025404    0.0  Chm223
2063   m     75.0  LIGHT YELLOW  0.177253 -0.039663 -0.026948    0.0  Chm223
2064   m     75.0  LIGHT YELLOW  0.181301 -0.043369 -0.026798    0.0  Chm223
2065   m     75.0  LIGHT YELLOW  0.175782 -0.040899 -0.025851    0.0  Chm223
2066   m     75.0  LIGHT YELLOW  0.177724 -0.040984 -0.025238    0.0  Chm223

[2067 rows x 8 columns]

In [65]:
AE_Data

,Пол,Возраст,Цвет,0,1,2,3,4,5,TOTAL,Dataset
0,m,24.0,COLORLESS,-1.615935,0.656887,0.155497,2.215795,-1.949322,2.180748,8.0,Chm1
1,m,24.0,COLORLESS,-1.512113,0.622592,0.067402,2.297075,-2.029424,2.209814,8.0,Chm1
2,m,24.0,COLORLESS,-1.637082,0.669989,0.195597,2.254537,-2.017076,2.257585,8.0,Chm1
3,m,24.0,COLORLESS,-1.567082,0.633607,0.126719,2.308670,-2.010207,2.200638,8.0,Chm1
4,m,24.0,COLORLESS,-1.665378,0.683606,0.226184,2.242529,-2.001230,2.261053,8.0,Chm1
...,...,...,...,...,...,...,...,...,...,...,...
2062,m,75.0,LIGHT YELLOW,-1.763212,0.653398,0.159762,2.638638,-2.243226,2.268825,0.0,Chm223
2063,m,75.0,LIGHT YELLOW,-1.758184,0.651057,0.156949,2.644888,-2.248323,2.271011,0.0,Chm223
2064,m,75.0,LIGHT YELLOW,-1.744788,0.639681,0.144954,2.651663,-2.245126,2.254853,0.0,Chm223
2065,m,75.0,LIGHT YELLOW,-1.759087,0.640923,0.153861,2.643310,-2.244013,2.256964,0.0,Chm223
2066,m,75.0,LIGHT YELLOW,-1.755542,0.644836,0.156322,2.645764,-2.241987,2.260785,0.0,Chm223

# train_test_split by Chms

In [66]:
chms = PCA_Data.Dataset.unique()

In [67]:
train_chms, test_chms, _, _, = train_test_split(chms,chms, test_size=0.2, random_state=42)

In [68]:
train_inds = list(map(lambda x: x in train_chms, AE_Data.Dataset))
test_inds = list(map(lambda x: x in test_chms, AE_Data.Dataset))

In [69]:
AE_Data[train_inds]

,Пол,Возраст,Цвет,0,1,2,3,4,5,TOTAL,Dataset
0,m,24.0,COLORLESS,-1.615935,0.656887,0.155497,2.215795,-1.949322,2.180748,8.0,Chm1
1,m,24.0,COLORLESS,-1.512113,0.622592,0.067402,2.297075,-2.029424,2.209814,8.0,Chm1
2,m,24.0,COLORLESS,-1.637082,0.669989,0.195597,2.254537,-2.017076,2.257585,8.0,Chm1
3,m,24.0,COLORLESS,-1.567082,0.633607,0.126719,2.308670,-2.010207,2.200638,8.0,Chm1
4,m,24.0,COLORLESS,-1.665378,0.683606,0.226184,2.242529,-2.001230,2.261053,8.0,Chm1
...,...,...,...,...,...,...,...,...,...,...,...
2062,m,75.0,LIGHT YELLOW,-1.763212,0.653398,0.159762,2.638638,-2.243226,2.268825,0.0,Chm223
2063,m,75.0,LIGHT YELLOW,-1.758184,0.651057,0.156949,2.644888,-2.248323,2.271011,0.0,Chm223
2064,m,75.0,LIGHT YELLOW,-1.744788,0.639681,0.144954,2.651663,-2.245126,2.254853,0.0,Chm223
2065,m,75.0,LIGHT YELLOW,-1.759087,0.640923,0.153861,2.643310,-2.244013,2.256964,0.0,Chm223
2066,m,75.0,LIGHT YELLOW,-1.755542,0.644836,0.156322,2.645764,-2.241987,2.260785,0.0,Chm223

In [77]:
AE_Train_X = AE_Data[train_inds].drop(['TOTAL', 'Dataset'], axis=1)
AE_Train_y = AE_Data[train_inds]['TOTAL']

AE_Test_X = AE_Data[test_inds].drop(['TOTAL', 'Dataset'], axis=1)
AE_Test_y = AE_Data[test_inds]['TOTAL']


PCA_Train_X = PCA_Data[train_inds].drop(['TOTAL', 'Dataset'], axis=1)
PCA_Train_y = PCA_Data[train_inds]['TOTAL']

PCA_Test_X = PCA_Data[test_inds].drop(['TOTAL', 'Dataset'], axis=1)
PCA_Test_y = PCA_Data[test_inds]['TOTAL']